# Generated by Django 5.2.2 on 2025-06-23 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_add_actor_field'),
        ('social', '0003_media_media_type_notification_story_follow'),
    ]

    operations = [
    ]
